##### Stoke config file with most permissive instruction selection -- only prohibit opcodes in the denylist

# prohibit floating-point variants, jumps, vector/packed instructions
--opc_blacklist "{ cmpxchg.* .*pd.* .*ps.* .*sd.* .*ss.* f.* j.* v.* p.* .*rh.* .*div.* .*xadd.* }"
--validator_must_support

--def_in "{ %rdi %rsi %rdx %rcx }" # The registers that are defined on entry to the target
--live_out "{ %rax }" # The registers that are live on exit from the target

--training_set "{ 0 ... 999 }" # Testcases to use for measuring correctness during search
--test_set "{ 1000 ... 1023 }"  # Testcases to use as holdout set for checking correctness

--distance hamming # Metric for measuring error between live-outs
--misalign_penalty 1 # Penalty for results that appear in the wrong location
--reduction sum # Method for summing errors across testcases
--sig_penalty 9999 # Score to assign to rewrites that produce non-zero signals

--global_swap_mass 1 # Proposal mass
--instruction_mass 1 # Proposal mass
--local_swap_mass 1 # Proposal mass
--opcode_mass 1 # Proposal mass
--operand_mass 1 # Proposal mass
--rotate_mass 1 # Proposal mass
--opcode_width_mass 1

--beta 1 # Search annealing constant

--statistics_interval 24000000 # Print statistics every 24m proposals
--timeout_iterations 2400000000 # Propose 2400m modifications total before giving up
--cycle_timeout 10000000 # Try 10m modifications before restarting
--timeout_seconds 28800 # Time out overall search after 8 hours

--strategy leakage # Verify that results do not leak according to current semantics
--leakage_reduction value_ranges
--solver_timeout 240000 # Time out solver queries after 240k ms (4 min)
--failed_verification_action add_all_counterexamples

--cost "correctness + 20 * leakage + 2 * latency"
--cost_logging "correctness,leakage,latency,size,binsize"
--postprocessing simple
--cpu_flags "{ }"
