// Auto-generated leakage range mappings
// Generated from leakage semantics

#ifndef STOKE_LEAKAGE_RANGES_H
#define STOKE_LEAKAGE_RANGES_H

#include <unordered_map>
#include <vector>
#include <tuple>
#include "src/ext/x64asm/include/x64asm.h"

namespace stoke {
enum class OperandID {
    R1, R2, R3,
    R1_2, R2_2, R3_2,
    Imm8, Imm16, Imm32, Imm64,
    RAX, RBX, RCX, RDX, RSI, RDI, R8, R9, R10, R11, R12, R13, R14, R15,
    NotSupported
};

inline OperandID get_operand_id(const x64asm::Instruction& inst, size_t index, bool second_inst = false) {
  switch (inst.type(index)) {
    // General purpose registers
    case x64asm::Type::AL:
    case x64asm::Type::AX:
    case x64asm::Type::EAX:
    case x64asm::Type::RAX:
      return OperandID::RAX;
    case x64asm::Type::DX:
      return OperandID::RDX;
    case x64asm::Type::CL:
      return OperandID::RCX;
    // Unspecified registers
    case x64asm::Type::RH:
    case x64asm::Type::R_8:
    case x64asm::Type::R_16:
    case x64asm::Type::R_32:
    case x64asm::Type::R_64:
      // Requires special handling: k-framework semantics "flip" the numbering order of register
      // operands compared to stoke. I.e., R3 always precedes R2, which always precedes R1.
      if (inst.arity() > 3) {
        // No support for instructions with arity > 3
        return OperandID::NotSupported;
      }
      switch(index) {
        case 0:
          switch(inst.arity()) {
            case 1:
              return second_inst ? OperandID::R1_2 : OperandID::R1;
            case 2:
              return second_inst ? OperandID::R2_2 : OperandID::R2;
            default: // arity 3
              return second_inst ? OperandID::R3_2 : OperandID::R3;
          }
        case 1:
          switch(inst.arity()) {
            case 2:
              return OperandID::R1;
            default: // arity 3
              return OperandID::R2;
          }
        default: // index 2
          return OperandID::R1;
      }
    // Immediates
    case x64asm::Type::IMM_8:
      return OperandID::Imm8;
    case x64asm::Type::IMM_16:
      return OperandID::Imm16;
    case x64asm::Type::IMM_32:
      return OperandID::Imm32;
    case x64asm::Type::IMM_64:
      return OperandID::Imm64;
    // All others not supported
    default:
      return OperandID::NotSupported;
  }
}
}

namespace std {
template<>
struct hash<x64asm::Opcode> {
  std::size_t operator()(const x64asm::Opcode& opcode) const {
    return std::hash<int32_t>()(static_cast<int32_t>(opcode));
  }
};

template<>
struct hash<stoke::OperandID> {
  std::size_t operator()(const stoke::OperandID& operandId) const {
    return std::hash<int32_t>()(static_cast<int32_t>(operandId));
  }
};

inline ostream& operator<<(ostream& os, const stoke::OperandID& opid) {
  switch (opid)
  {
  case stoke::OperandID::R1:
    os << "R1";
    return os;
  case stoke::OperandID::R2:
    os << "R2";
    return os;
  case stoke::OperandID::R3:
    os << "R3";
    return os;
  case stoke::OperandID::Imm8:
    os << "Imm8";
    return os;
  case stoke::OperandID::Imm16:
    os << "Imm16";
    return os;
  case stoke::OperandID::Imm32:
    os << "Imm32";
    return os;
  case stoke::OperandID::Imm64:
    os << "Imm64";
    return os;
  case stoke::OperandID::RAX:
    os << "RAX";
    return os;
  case stoke::OperandID::RCX:
    os << "RCX";
    return os;
  case stoke::OperandID::RDX:
    os << "RDX";
    return os;
  case stoke::OperandID::NotSupported:
    os << "NotSupported";
    return os;
  default:
    os << "Unexpected OperandID";
    return os;
  }
}
}

namespace stoke {

// Partition: a list of (low, high) value ranges, representing a partition for one input value
struct Partition {
    std::vector<std::tuple<uint64_t, uint64_t>> ranges;

    bool contains(uint64_t value) const {
        for (const auto& range : ranges) {
            uint64_t low = std::get<0>(range);
            uint64_t high = std::get<1>(range);
            if (value >= low && value <= high) {
                return true;
            }
        }
        return false;
    }
};

// EquivalenceClass: a list of maps relating operand names to partitions, representing the value
// ranges for that operand
struct EquivalenceClass {
    std::vector<std::unordered_map<OperandID, Partition>> partitions;
};

// Map from opcode to pair of vectors: first vector for operand 0 (R1/src), second for operand 1 (R2/dst)
// Each vector contains partitions, where each partition represents ranges from one equivalence class
static std::unordered_map<x64asm::Opcode, std::vector<EquivalenceClass>> leakage_ranges = {
    {x64asm::ADD_AX_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::ADD_EAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::ADD_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::ADD_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::ADD_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::ADD_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::ADD_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::ADD_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::ADD_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::ADD_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::ADD_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::ADD_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::ADD_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::ADD_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::ADD_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ADD_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ADD_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ADD_RAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::AND_AX_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::AND_EAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::AND_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::AND_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::AND_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::AND_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::AND_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::AND_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::AND_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::AND_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::AND_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::AND_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::AND_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::AND_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::AND_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::AND_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::AND_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::AND_RAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::CMP_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}}},
    {x64asm::CMP_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}}},
    {x64asm::CMP_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}}},
    {x64asm::CMP_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}}},
    {x64asm::CMP_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::CMP_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::CMP_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}}},
    {x64asm::CMP_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}}},
    {x64asm::IMUL_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 65535UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 65535UL)}}}}}}}},
    {x64asm::IMUL_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(2UL, 65535UL)}}}}}}}},
    {x64asm::IMUL_R16_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 65535UL)}}}}}}}},
    {x64asm::IMUL_R16_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 65535UL)}}}}}}}},
    {x64asm::IMUL_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 4294967295UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 4294967295UL)}}}}}}}},
    {x64asm::IMUL_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(2UL, 4294967295UL)}}}}}}}},
    {x64asm::IMUL_R32_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 4294967295UL)}}}}}}}},
    {x64asm::IMUL_R32_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 4294967295UL)}}}}}}}},
    {x64asm::IMUL_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::IMUL_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::IMUL_R64_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::IMUL_R64_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::IMUL_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 255UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 255UL)}}}}}}}},
    {x64asm::MUL_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 65535UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 65535UL)}}}}}}}},
    {x64asm::MUL_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 4294967295UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 4294967295UL)}}}}}}}},
    {x64asm::MUL_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::MUL_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(1UL, 1UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(2UL, 255UL)}}}, {OperandID::RAX, Partition{{std::make_tuple(2UL, 255UL)}}}}}}}},
    {x64asm::NEG_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::NEG_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::NEG_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::NEG_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::OR_AX_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::OR_EAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::OR_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::OR_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::OR_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::OR_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::OR_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::OR_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::OR_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::OR_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::OR_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::OR_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::OR_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::OR_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::OR_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::OR_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::OR_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::OR_RAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::ROL_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROL_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::ROL_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::ROL_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROL_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::ROL_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::ROL_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROL_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::ROL_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::ROL_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROL_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::ROL_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::ROR_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROR_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::ROR_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::ROR_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROR_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::ROR_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::ROR_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROR_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::ROR_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::ROR_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::ROR_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::ROR_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::SAL_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAL_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SAL_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SAL_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAL_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SAL_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SAL_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAL_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SAL_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SAL_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAL_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAL_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAR_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAR_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::SAR_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::SAR_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAR_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::SAR_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::SAR_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAR_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::SAR_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::SAR_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SAR_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::SAR_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::SHL_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHL_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SHL_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SHL_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHL_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SHL_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SHL_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHL_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SHL_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SHL_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHL_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHL_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R16_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SHR_R16_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65535UL)}}}}}}}},
    {x64asm::SHR_R32_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SHR_R32_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967295UL)}}}}}}}},
    {x64asm::SHR_R64_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SHR_R64_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SHR_R8_CL, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::RCX, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SHR_R8_ONE, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 255UL)}}}}}}}},
    {x64asm::SUB_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}}},
    {x64asm::SUB_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}}}}},
    {x64asm::SUB_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}}},
    {x64asm::SUB_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}}}}},
    {x64asm::SUB_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SUB_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}}}}},
    {x64asm::SUB_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}}},
    {x64asm::SUB_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}}}}},
    {x64asm::TEST_AX_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::TEST_EAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::TEST_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::TEST_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::TEST_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::TEST_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::TEST_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::TEST_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::TEST_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::TEST_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::TEST_RAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::XOR_AX_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::XOR_EAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::XOR_R16_IMM16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::XOR_R16_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::XOR_R16_R16, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::XOR_R16_R16_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 65535UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 65535UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(65535UL, 65535UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 65534UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 65534UL)}}}}}}}},
    {x64asm::XOR_R32_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::XOR_R32_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::XOR_R32_R32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::XOR_R32_R32_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 4294967295UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 4294967295UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(4294967295UL, 4294967295UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 4294967294UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 4294967294UL)}}}}}}}},
    {x64asm::XOR_R64_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::XOR_R64_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::XOR_R64_R64, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::XOR_R64_R64_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 18446744073709551615UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}},
    {x64asm::XOR_R8_IMM8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::XOR_R8_R8, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::XOR_R8_R8_1, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 255UL)}}}}, std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(0UL, 255UL)}}}, {OperandID::R2, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(255UL, 255UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::R1, Partition{{std::make_tuple(1UL, 254UL)}}}, {OperandID::R2, Partition{{std::make_tuple(1UL, 254UL)}}}}}}}},
    {x64asm::XOR_RAX_IMM32, std::vector<EquivalenceClass>{EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(0UL, 0UL), std::make_tuple(18446744073709551615UL, 18446744073709551615UL)}}}}}}, EquivalenceClass{{std::unordered_map<OperandID, Partition>{{OperandID::RAX, Partition{{std::make_tuple(1UL, 18446744073709551614UL)}}}}}}}}
};

} // namespace stoke

#endif // STOKE_LEAKAGE_RANGES_H
